"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hr1=jtrr3xp^f$kg6&8f2b)#$5f4^_#c0du9l3m%2-mhvzn-j&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AZAMPAY = {
#     "BASE_URL": "https://sandbox.azampay.co.tz",
#     "APP_ID": "f5f66619-bfd8-4375-8b79-0b7caa642692",
#     "APP_SECRET": "FZpjnMnIUf/C5n3e9xk2R2t48eTM4qvdb53f1Cnl7CqO2ojDMfVu9Udsx6YJiHKtRxbsKfVuRoA8oetTGOzD13GtyfVbYthZdzrS7s8hWwXP9lnWRR13EPE3Tf04hU98aynXbgZ5mZkvGGwNTOUI8yCcVfEimTCgMIgRYOCXD+VJ3Gwqlgi4kIoDz9z7eRPnOlTJbRaNDjezU5uX0GaM2vx3mHECsA/KoPPSNFlTE6UXIZJKXSuPxaaYxwMs0QmlLcx6sIh3mJeua7Gg7kdRs0kWzI6WYDHn2vivYzxrY+Di7HFn5j1y9fS8kQYAEbGipjyXGLzFK2/FBn4L2xT+fdVBgRFmGPp4XvVttTL7FOUNibl3l2SuzYq0ddIlTAde108xI8vgE7ln6umyRBI/9gJloVaMbGHwlQHuxVeZF3NYGQEWvIBjK9Wzazha/tUAjx7vaCuM7v/CgUb6Ml/2uDS7e+/UAbY0+tHiHfHXQ9FRrLCd1+aI08idflbEM0xSqeXVOIZ9JTR/J2PogRRCa5yoO7sGyok868kyghQBoKKYoMzukgOyvgAszBhGE34pHALF2aKC2a/mRR5/9AqhNf/yPhI246Tqg7fb1NE+zc52wBFKJTU6UcdVSkgLtuABsZjNPKSKLlfLfX9wmtcuW7cPF5uN5pFEaX7tycgzeEk=",
#     # "MERCHANT_ACCOUNT": "your_merchant_account",
# }



